# Generated by Django 5.2.8 on 2025-11-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daftarsanggar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sanggar",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
