# Generated by Django 5.2.8 on 2025-11-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daftarsanggar", "0002_sanggar_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sanggar",
            name="image_url",
        ),
        migrations.AddField(
            model_name="sanggar",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
